# Generated by Django 5.2.6 on 2025-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('loco_number', models.CharField(blank=True, max_length=100, null=True)),
                ('train_number', models.CharField(blank=True, max_length=100, null=True)),
                ('lp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('cab_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('safety_score', models.FloatField(default=0)),
                ('report_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
