# Generated by Django 5.2.6 on 2025-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
