# Generated by Django 5.2.6 on 2025-10-27 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_analysisresult_message_analysisresult_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrecord',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='cab_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='loco_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='lp_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='lp_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='report_path',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='safety_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='train_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='cab_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
