# Generated by Django 5.2.6 on 2025-10-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_analysisrecord_upload_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='cab_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
