# Generated by Django 5.2.6 on 2025-10-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_analysisresult_cab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='cab_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
