from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from datetime import datetime
import os

def generate_analysis_report(output_dir, context):
    os.makedirs(output_dir, exist_ok=True)
    filename = f"{context.get('train_number', 'Unknown')}_report.pdf"
    report_path = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(report_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b><font size=16 color='navy'>Railway Safety Monitoring Report</font></b>", styles['Title']))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%d-%b-%Y %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Table with dynamic info
    data = [
        ["Date", context.get("date", "N/A")],
        ["Time", context.get("time", "N/A")],
        ["Loco Number", context.get("loco_number", "N/A")],
        ["Train Number", context.get("train_number", "N/A")],
        ["Loco Pilot Name", context.get("lp_name", "N/A")],
        ["Loco Pilot ID", context.get("lp_id", "N/A")],
        ["Cab Type", context.get("cab_type", "N/A")],
        ["Analyzed Video", context.get("video_name", "N/A")],
        ["Safety Score", f"{context.get('safety_score', 'N/A')} %"],
        ["Remarks", context.get("remarks", "N/A")],
    ]

    table = Table(data, colWidths=[150, 300])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("<b>Note:</b> Auto-generated by Railway Safety Monitoring System.", styles['Italic']))

    doc.build(elements)
    return report_path
